[tool.black]
target-version = ['py39']
line-length = 120
exclude = '''
(
    venv
)
'''

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 88
skip = '.env,venv'
src_paths = ['./src']


