from shared.collections import Enum


class Layer7Methods(Enum):
    CFB = "CFB"
    BYPASS = "BYPASS"
    GET = "GET"
    POST = "POST"
    OVH = "OVH"
    STRESS = "STRESS"
    DYN = "DYN"
    SLOW = "SLOW"
    HEAD = "HEAD"
    NULL = "NULL"
    COOKIE = "COOKIE"
    PPS = "PPS"
    EVEN = "EVEN"
    GSB = "GSB"
    DGB = "DGB"
    AVB = "AVB"
    CFBUAM = "CFBUAM"
    APACHE = "APACHE"
    XMLRPC = "XMLRPC"
    BOT = "BOT"
    BOMB = "BOMB"
    DOWNLOADER = "DOWNLOADER"
    KILLER = "KILLER"


class Layer4Methods(Enum):
    TCP = "TCP"
    UDP = "UDP"
    SYN = "SYN"
    VSE = "VSE"
    MINECRAFT = "MINECRAFT"
    MEM = "MEM"
    NTP = "NTP"
    DNS = "DNS"
    ARD = "ARD"
    CHAR = "CHAR"
    RDP = "RDP"
    MCBOT = "MCBOT"
    CONNECTION = "CONNECTION"
    CPS = "CPS"
    FIVEM = "FIVEM"
    TS3 = "TS3"
    MCPE = "MCPE"
    CLDAP = "CLDAP"
